config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  
  get    'login', to: 'user_sessions#new', as: 'login'
  post   'login', to: 'user_sessions#create'
  get    'logout', to: 'user_sessions#destroy', as: 'logout'
  
  get    'join', to: 'users#new', as: 'join'
  post   'join', to: 'users#create'
  
  get    'confirm-email/:token', to: 'users#confirm_email', as: 'confirm_email'
  
  get    'account', to: 'users#edit', as: 'account'
  patch  'account', to: 'users#update'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.maintain_sessions = false
    c.crypto_provider = Authlogic::CryptoProviders::BCrypt
    c.merge_validates_length_of_password_field_options minimum: 0
    c.merge_validates_length_of_password_confirmation_field_options minimum: 0
  end
  include Authlogic::ActsAsAuthentic::EmailToken::Confirmation
  
  has_many :folders
  has_many :uploads
  
  validates(:password, if: :require_password?,
            password_strength: {min_entropy: 15, use_dictionary: true, message: "isn't strong enough."})
  
  def activate
    self.activated = true
  end
  
  def self.find_by_login_or_email(val)
    unless has_login_field?
      raise "Trying to find_by_login_or email, but User model doesn't have login column"
    end
    where(['login = ? OR email = ?', val, val]).first
  end
  
  def self.has_login_field?
    columns.map(&:name).include?('login')
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_login_or_email if User.has_login_field?
  
  validate :must_be_activated
	
	def bad_credentials?
	  errors.include?(:login) or errors.include?(:email) or errors.include?(:password)
	end
	
	private
	
	def must_be_activated
	  if attempted_record and !attempted_record.activated
      errors.add(:activation, 'You have not yet activated your account.')
    end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  before_filter :require_user
  
  # These match the alert class names in Bootstrap. (You can still use them even if you
  # don't use Bootstrap, though.)
  add_flash_types :success, :info, :warning, :danger
  
  def current_user_session
		return @current_user_session if defined?(@current_user_session)
		@current_user_session = UserSession.find
	end

	def current_user
		return @current_user if defined?(@current_user)
		@current_user = current_user_session && current_user_session.record
	end
	
	def require_admin
	  unless current_user and current_user.admin
	    store_location
	    redirect_to login_url
			return false
	  end
	end
	
	def require_no_user
	  if current_user
			redirect_to root_url, notice: 'You must be logged out to access that page.'
			return false
	  end
	end
	
	def require_user
		unless current_user
			store_location
			redirect_to login_url, notice: 'You must be logged in to access that page.'
			return false
		end
	end
	
	def store_location(loc = nil)
		session[:return_to] = loc || request.fullpath
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :require_user, only: [:home]
  
  def home
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_filter :require_user, :only => [:new, :create]

	def new
	  if session[:return_to].blank? and !request.env['HTTP_REFERER'].blank?
  		store_location request.env['HTTP_REFERER']
  	end
		@user_session = UserSession.new
	end

	def create
		@user_session = UserSession.new user_session_params
		if @user_session.save
      return_to = session[:return_to]
      session[:return_to] = nil
      redirect_to(return_to || root_url)
		else
			render :action => :new
		end
	end

	def destroy
		current_user_session.destroy
		redirect_to login_url, info: "You've been logged out."
	end
	
	private
	
	def user_session_params
	  params.require(:user_session).permit(:login, :email, :password, :remember_me)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_user, only: [:new, :create, :confirm_email]
  before_filter :require_no_user, only: [:new, :create]
  
  def confirm_email
    if user = User.find_using_email_token(params[:token], 5.days)
      was_unactivated = !user.activated
      user.confirm_email!
      UserSession.create(user)
      if was_unactivated
        redirect_to root_url, success: 'Your account has been activated.'
      else
        redirect_to root_url, success: 'Your email address has been confirmed.'
      end
    else
      render action: :bad_confirmation_email
    end
  end
    
  def create
    @user = User.new new_user_params
    if @user.save
			@user.maybe_deliver_email_confirmation! self
			redirect_to root_url, success: "Thanks for joining. Please check your email for instructions on activating your account."
		else
			render action: :new
		end
  end
  
  def edit
  end
  
  def new
    @user = User.new
  end
  
  def update
    @user = current_user
    if @user.update_attributes existing_user_params
      if @user.maybe_deliver_email_confirmation! self
        notice = 
          'An email has been sent to your new address. Please follow the instructions in ' +
          'that email to confirm your new address. Until then, we will continue to use ' + 
          'your old address.'
      else
        notice = 'Account settings saved.'
      end
      if params[:user][:password].present?
        notice << ' Your password has been changed. Please log back in with your new password.'
        redirect_to login_url, success: notice
      else
        redirect_to account_url, success: notice
      end
    else
      render action: :edit
    end
  end
  
  private
  
  def existing_user_params
    params.require(:user).permit([:new_email] + common_user_params)
  end
        
  def new_user_params
    permitted = [:email] + common_user_params
    permitted << [:login] if User.has_login_field?
    params.require(:user).permit(permitted)
  end
  
  def common_user_params
    [:password, :password_confirmation, :time_zone]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    params[:controller].gsub('_', '-').gsub('/', '-') + '-' +
    params[:action].gsub('_', '-')
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def alert(*args, &block)
    options = args.extract_options!
    options.reverse_merge! type: :info
    
    if block_given?
      message = capture(&block)
    else
      message = args.first
    end
    
    alert_classes = ['alert', "alert-#{options[:type]}"]
    if options[:dismissible]
      alert_classes << 'alert-dismissible'
    end
    
    content_tag 'div', class: alert_classes.join(' '), role: 'alert' do
      out = ''.html_safe
      if options[:dismissible]
        out << content_tag('button', type: 'button', class: 'close', 'data-dismiss' => 'alert') do
          content_tag('span', '&times;'.html_safe, 'aria-hidden' => true) +
          content_tag('span', 'Close', class: 'sr-only')
        end
      end
      out + content_tag('div', message)
    end
  end
end

class ActionView::Helpers::FormBuilder
  def error_on(attr, options = {})
    options.reverse_merge! capitalize: true
    if object.errors.include? attr
      @template.content_tag('span', class: 'help-block') do
        object.errors[attr].map do |error|
          options[:capitalize] ? error.capitalize : error
        end.join(options[:capitalize] ? '. ': '; ')
      end
    else
      nil
    end
  end
  
  def group(attr)
    classes = ['form-group']
    if object.errors.include? attr
      classes << 'has-error'
    end
    @template.content_tag('div', class: classes.join(' ')) do
      yield
    end
  end
end

app/views/layouts/_alert.html.erb
<% if flash[type].present? %>
  <div class="alert alert-<%= type %> alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    <span class="sr-only">Close</span></button>
    <div class="container"><%= flash[type] %></div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_url, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link</a></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'Log out', logout_url %></li>
          <li><%= link_to 'Account', account_url %></li>
        <% else %>
          <li><%= link_to 'Log in', login_url %></li>
          <li><%= link_to 'Join', join_url %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Page Title</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="<%= body_class %>">
  <%= render partial: 'layouts/navbar' %>
  
  <div class="container">
    <% [:danger, :warning, :info, :success].each do |type| %>
      <% if flash[type].present? %>
        <%= alert(flash[type], type: type, dismissible: true) %>
      <% end %>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/user_sessions/new.html.erb
<%= form_for @user_session, url: login_path do |f| %>
  <% if @user_session.bad_credentials? %>
      <% if User.has_login_field? %>
        <%= alert 'Incorrect login or password.', type: :danger %>
      <% else %>
        <%= alert 'Incorrect email or password.', type: :danger %>
      <% end %>
  <% elsif @user_session.errors.include?(:activation) %>
    <%= alert 'Your account has not been activated.', type: :danger %>
  <% end %>
  
  <%= f.group :login do %>
    <% if User.has_login_field? %>
      <%= f.label :login, 'Login:' %>
      <%= f.text_field :login, class: 'form-control' %>
    <% else %>
      <%= f.label :email, 'Email:' %>
      <%= f.text_field :email, class: 'form-control' %>
    <% end %>
  <% end %>

  <%= f.group :login do %>
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, class: 'form-control' %>
  <% end %>
  
  <div class="checkbox">
    <%= f.label :remember_me do %>
      <%= f.check_box :remember_me %>
      Remember me
    <% end %>
  </div>
  
  <button type="submit" class="btn btn-default">Log in</button>
<% end %>

app/views/users/_password_strength_instructions.html.erb
<p class="help-block">A strong password is required. Use numbers, mixed-case letters,
and symbols. Use at least eight characters. Avoid common passwords.</span>

app/views/users/edit.html.erb
<% if current_user.email_change_unconfirmed? %>
  <%= alert(type: :info, dismissible: true) do %>
    Your email address (<%= current_user.new_email %>) has not been confirmed yet. In the
    meantime, emails will continue to be sent to <%= current_user.email %>.
  <% end %>
<% end %>

<h1>Account</h1>

<%= form_for current_user, url: account_url do |f| %>
  <%= f.group :new_email do %>
    <%= f.label :new_email, 'Email address:' %>
    <%= f.text_field :new_email, class: 'form-control' %>
    <%= f.error_on :new_email %>
  <% end %>
  
  <%= f.group :password do %>
    <%= f.label :password, 'Change password (or leave blank for no change):' %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.error_on :password %>
    <%= render partial: 'users/password_strength_instructions' %>
  <% end %>
  
  <%= f.group :password_confirmation do %>
    <%= f.label :password_confirmation, 'Confirm new password (or leave blank for no change):' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.error_on :password_confirmation %>
  <% end %>
  
  <%= f.group :time_zone do %>
    <%= f.label :time_zone, 'Time zone:' %>
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: 'Eastern Time (US & Canada)', class: 'form-control' %>
    <%= f.error_on :time_zone %>
  <% end %>
  
  <button type="submit" class="btn btn-default">Save</button>
<% end %>

app/views/users/new.html.erb
<h1>Join</h1>

<%= form_for @user, url: join_url do |f| %>
  <% if User.has_login_field? %>
    <%= f.group :login do %>
      <%= f.label :login, 'Username:' %>
      <%= f.text_field :login, class: 'form-control' %>
      <%= f.error_on :login %>
    <% end %>
  <% end %>
  
  <%= f.group :email do %>
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, class: 'form-control' %>
    <%= f.error_on :email %>
  <% end %>
  
  <%= f.group :password do %>
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.error_on :password %>
    <%= render partial: 'users/password_strength_instructions' %>
  <% end %>
  
  <%= f.group :password_confirmation do %>
    <%= f.label :password_confirmation, 'Confirm password:' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <%= f.error_on :password_confirmation %>
  <% end %>
  
  <%= f.group :time_zone do %>
    <%= f.label :time_zone, 'Time zone:' %>
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: 'Eastern Time (US & Canada)', class: 'form-control' %>
    <%= f.error_on :time_zone %>
  <% end %>
  
  <button type="submit" class="btn btn-default">Join</button>
<% end %>